Refactor location to address
AY2425S1-CS2103T-F13-2/tp pull request #158
Opened 2024-10-26 08:15 UTC by NgZiXin

Better fit use case

2024-10-27 07:58 UTC, leslieyip02 requested changes

2024-10-27 07:58 UTC, leslieyip02 commented on gradlew
> +address of your Java installation."
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on gradlew.bat
> +echo address of your Java installation.
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
> +     * @param prefsFilePath address of the data. Cannot be null.
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on src/main/java/seedu/address/storage/buyer/JsonBuyerListStorage.java
> +     * @param filePath address of the data. Cannot be null.
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on src/main/java/seedu/address/storage/buyer/JsonBuyerListStorage.java
> +     * @param filePath address of the data. Cannot be null.
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on src/main/java/seedu/address/storage/meetup/JsonMeetUpListStorage.java
> +     * @param filePath address of the data. Cannot be null.
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on src/main/java/seedu/address/storage/meetup/JsonMeetUpListStorage.java
> +     * @param filePath address of the data. Cannot be null.
I don't think this is correct.

2024-10-27 07:58 UTC, leslieyip02 commented on src/main/java/seedu/address/ui/buyer/BuyerCard.java
> +     * Note: Certain keywords such as "address" and "resources" are reserved keywords in JavaFX.
I don't think this is correct.

2024-10-27 08:03 UTC, CreditableX commented on src/main/java/seedu/address/ui/property/PropertyCard.java
> +     * Note: Certain keywords such as "address" and "resources" are reserved keywords in JavaFX.
Perhaps this is not correct...

2024-10-27 08:04 UTC, NgZiXin commented on gradlew
> +address of your Java installation."
yup, changing that thanks!

2024-10-28 08:26 UTC, KennyLewi commented on gradlew
> +address of your Java installation."
i think this is correct.

2024-10-28 08:26 UTC, KennyLewi commented on gradlew.bat
> +echo address of your Java installation.
i think this is correct now.

2024-10-28 08:26 UTC, KennyLewi commented on src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
> +     * @param prefsFilePath address of the data. Cannot be null.
i think this is correct now.

2024-10-28 08:26 UTC, KennyLewi commented on src/main/java/seedu/address/storage/buyer/JsonBuyerListStorage.java
> +     * @param filePath address of the data. Cannot be null.
i think this is correct now.

2024-10-28 08:26 UTC, KennyLewi commented on src/main/java/seedu/address/storage/buyer/JsonBuyerListStorage.java
> +     * @param filePath address of the data. Cannot be null.
i think this is correct now.

2024-10-28 08:26 UTC, KennyLewi commented on src/main/java/seedu/address/storage/meetup/JsonMeetUpListStorage.java
> +     * @param filePath address of the data. Cannot be null.
i think this is correct now.

2024-10-28 08:26 UTC, KennyLewi commented on src/main/java/seedu/address/storage/meetup/JsonMeetUpListStorage.java
> +     * @param filePath address of the data. Cannot be null.
i think this is correct now.

2024-10-28 08:28 UTC, KennyLewi reviewed
LGTM

2024-10-28 08:28 UTC, KennyLewi commented on src/test/java/seedu/address/testutil/property/TypicalProperties.java
> +            .withAddress(VALID_ADDRESS_BOB).build();
LGTM

2024-10-28 08:28 UTC, merged